version: '3.2'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - prometheus-net
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus:ro
    depends_on:
      - cadvisor
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      # - "--web.external-url=http://localhost:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - prometheus-net
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  # alertmanager:
  #   image: prom/alertmanager:latest
  #   container_name: alertmanager
  #   networks:
  #     - prometheus-net
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./docker/alertmanager:/etc/alertmanager
  #   command:
  #     - "--config.file=/etc/alertmanager/alertmanager.yml"
  #     - "--web.external-url=http://localhost:9093"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - prometheus-net
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    container_name: redis
    networks:
      - prometheus-net
    ports:
      - "6379:6379"

networks:
  prometheus-net: